setup:
  seed: 8
  use_gpu: False

train:
  name: 'LunarLanderContinuous-v2'
  n_episodes: 1001
  verbose: 50

agent:
  gamma: 0.99 #0.99
  tau: 0.0005 #0.005

  alpha: .5
  alpha_scale: True
  alpha_decay: .996
  alpha_min: .0001

  std_scale: True
  std_decay: .996 # original: .99
  std_min: 0.01
  std: 1 # original: 1
  
  buffer:
    size: 10000
    batch: 1024 # origi: 128

  actor:
    h_layers: 2
    h_size: 64
    print_model: False

  critic:
    h_state_layers: 0
    h_state_size: 8
    h_action_layers: 0
    h_action_size: 2
    h_layers: 2
    h_size: 64
    print_model: False
  
      

