setup:
  seed: 3
  use_gpu: False

train:
  name: 'LunarLanderContinuous-v2'
  n_episodes: 1001
  verbose: 50

agent:
  gamma: 0.80
  tau: 0.1 # 0.005

  std_scale: True
  std_decay: .80 # .99
  std_min: 0.01
  std: 3 # 1
  
  buffer:
    size: 10000 
    batch: 256 # 128

  actor:
    h_layers: 2
    h_size: 7 # 64
    print_model: True

  critic:
    h_state_layers: 0
    h_state_size: 8
    h_action_layers: 0
    h_action_size: 2
    h_layers: 2
    h_size: 9 # 64
    print_model: True
  
      

