setup:
  seed: 3
  use_gpu: False

train:
  name: 'LunarLanderContinuous-v2'
  n_episodes: 1001
  verbose: 50

agent:
  gamma: 0.99 #0.99
  tau: 0.0005 #0.005

  alpha: .2
  alpha_scale: False
  alpha_decay: .994
  alpha_min: 0.01

  std_scale: True
  std_decay: .99 # original: .99
  std_min: 0.01
  std: 1 # original: 1
  
  buffer:
    size: 1000000
    batch: 128 # origi: 128

  actor:
    h_layers: 2
    h_size: 64
    print_model: False

  critic:
    h_state_layers: 0
    h_state_size: 8
    h_action_layers: 0
    h_action_size: 8
    h_layers: 2
    h_size: 64
    print_model: False
  
      

