setup:
  seed: 3
  use_gpu: False

train:
  name: 'LunarLanderContinuous-v2'
  n_episodes: 1001
  verbose: 50

agent:
  gamma: 0.99 #0.99
  tau: 0.005 #0.005

  alpha: .4
  alpha_scale: False
  alpha_decay: .994
  alpha_min: 0.01
  alpha_scaling_type: 'sigmoid_reward'

  std_scale: True
  std_decay: .995 # original: .99
  std_min: 0.01
  std: 1 # original: 1
  std_scaling_type: 'tanh_time'
  
  buffer:
    size: 100000
    batch: 512 # origi: 128

  actor:
    h_layers: 2
    h_size: 64
    print_model: False

  critic:
    h_state_layers: 0
    h_state_size: 32
    h_action_layers: 0
    h_action_size: 32
    h_layers: 2
    h_size: 64
    print_model: False
  
      

